name: indy-node-build-u1804
on: [ push, pull_request ]

jobs:
  indy-common:
    name: Build Indy Common
    runs-on: ubuntu-18.04
    #TODO: move this to hyperledger?
    container: udosson/indy-node-ci-u1804:latest
    strategy:
      matrix:
        module: [indy_common]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install .[tests]
        continue-on-error: true
        
      - name: Run Indy Common ${{ matrix.module }} test slice ${{ matrix.slice }}
        run: python3 -m pytest -l -vv --junitxml=test-result-plenum-${{ matrix.module }}-${{ matrix.slice }}.xml" --dir "${{ matrix.module }}" --output "test-result-indy-${{ matrix.slice }}.txt" --test-only-slice "${{ matrix.slice }}

  indy-node:
    name: Build Indy Node
    runs-on: ubuntu-18.04
    #TODO: move this to hyperledger?
    container: udosson/indy-node-ci-u1804:latest
    strategy:
      matrix:
        module: [indy_node]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install .[tests]
        continue-on-error: true
      
      - name: Run Indy Node ${{ matrix.module }} test slice ${{ matrix.slice }}
        run: python3 -m pytest -l -vv --junitxml=test-result-plenum-${{ matrix.module }}-${{ matrix.slice }}.xml" --dir "${{ matrix.module }}" --output "test-result-indy-${{ matrix.slice }}.txt" --test-only-slice "${{ matrix.slice }}

     

  lint:
    name: Lint
    runs-on: ubuntu-18.04
    #TODO: move this to hyperledger?
    container: udosson/indy-node-ci-u1804:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: flake8
        run: python3 -m flake8
