name: indy-node-build-u1804
on: [ push, pull_request ]

jobs:
  indy-common:
    name: Build Indy Common
    runs-on: ubuntu-18.04
    #TODO: move this to hyperledger?
    container: udosson/indy-node-ci-u1804:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install .[tests]
        continue-on-error: true
        
      - name: Run Indy Common test
        run: python3 -m pytest -l -vv --junitxml=test-result-indy-common.xml --dir indy_common --output "test-result-indy-common.txt"

  indy-node:
    name: Build Indy Node
    runs-on: ubuntu-18.04
    #TODO: move this to hyperledger?
    container: udosson/indy-node-ci-u1804:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install .[tests]
        continue-on-error: true
      
      - name: Run Indy Node test
        run: python3 -m pytest -l -vv --junitxml=test-result-indy-node.xml --dir indy_node --output "test-result-indy-node.txt"

     

  lint:
    name: Lint
    runs-on: ubuntu-18.04
    #TODO: move this to hyperledger?
    container: udosson/indy-node-ci-u1804:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: flake8
        run: python3 -m flake8
